AWSTemplateFormatVersion: "2010-09-09"

Resources:

  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "data-storage-${AWS::AccountId}"
      AccessControl: Private
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Function: !GetAtt Lambda.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: "UNPROCESSED"

  LambdaSourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "lambda-source-${AWS::AccountId}"
      AccessControl: Private

  DataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "DataTable"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "Timestamp"
          AttributeType: N
      KeySchema:
        - AttributeName: "Timestamp"
          KeyType: HASH

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      RoleName: "lambda_role"

  LambdaRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref LambdaRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: !GetAtt DataTable.Arn
          - Effect: Allow
            Action:
              - s3:GetBucketLocation
              - s3:ListBucket
            Resource: !GetAtt DataBucket.Arn
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectAcl
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:DeleteObject
            Resource: !Join
              - ''
              - - !GetAtt DataBucket.Arn
                - "/*"
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
      PolicyName: "lambda_role_policy"

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "lambda"
      Handler: "lambda_function.lambda_handler"
      Role: !GetAtt LambdaRole.Arn
      Code:
        S3Bucket: !Ref LambdaSourceBucket
        S3Key: "lambda.zip"
      Runtime: "python3.8"
      MemorySize: 512
      Timeout: 150
      ReservedConcurrentExecutions: 1